# Generated by Django 5.2.4 on 2025-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_videofile_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videofile",
            old_name="quantity",
            new_name="quality",
        ),
        migrations.AlterUniqueTogether(
            name="videofile",
            unique_together={("video", "quality")},
        ),
    ]
