# Generated by Django 5.2.4 on 2025-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_rename_quantity_videofile_quality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Видео файл"
            ),
        ),
    ]
