# Generated by Django 5.2.4 on 2025-07-23 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_videofile_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="videofile",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="video",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("video", "user"), name="unique_video_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="videofile",
            constraint=models.UniqueConstraint(
                fields=("video", "quality"), name="unique_video_quality"
            ),
        ),
    ]
